#include <stdio.h>
#include <stdlib.h>
#include <conio.h>
#include <string.h>
#define null 0

int main(void)
{
    printf("\n\t\t ---------------------------------------------------");
    printf("\n\t\t\t Array Element Checker by Aaradhy Sharma ");
    printf("\n\t\t ---------------------------------------------------");

    int array_1[20],input_search,i,counter = null;                  // initializing the variables //
    {
        for(i=0;i<20;i++)
        {
            printf("\n Enter a number to be input in the array : ");    //for loop to get the 20 numbers in the array input by the user //
            scanf("%d", &array_1[i]);
        }
    }

    printf("\n Please enter the number to be searched in the given array : ");  // taking a number as input_search to be searched in the array input by the user //
    scanf("%d",&input_search);

        if(i=0,i<20,i++)

        {
            if(array_1[i]==input_search)                                    // nested if loops to check if input_search is present in the array generated by the user //
            {
                counter++;
            }
        }



        if(counter)
        {
            printf("\n\n %d is present inside the matrix input by the user.",input_search);
        }
        else
        {
            printf("\n\n %d is NOT present inside the array input by the user.",input_search);
        }



    return 0;
}
